export const LIVEWEATHER_SAVE_START = 'LIVEWEATHER_SAVE_START';
export const LIVEWEATHER_SAVE_SUCCESS = 'LIVEWEATHER_SAVE_SUCCESS';
export const LIVEWEATHER_SAVE_FAILURE = 'LIVEWEATHER_SAVE_FAILURE';
